#!/bin/bash
set -eu

LUASRC="./src"
CFLAGS="-Wall -Wextra -std=c99 -pedantic -fPIC -shared -O2 -Wno-unused-label -g -I${LUASRC}"

#-------------------

cd "$(dirname "$0")"

modulename="$1"

lua_path="./examples/${modulename}.lua"
c_path="./generated/${modulename}.c"
so_path="./generated/${modulename}.so"

"$LUASRC/luaot" "$modulename" "$lua_path" > "$c_path"
gcc $CFLAGS "$c_path" -o "$so_path"
